### ISSUE TITLE
Mouse Move Delay

### ISSUE THREAD

**Issue by bobowk** [lstratman/EasyTabs#33] opened 2020-05-12 12:10 UTC
Hello!
I've recently noticed a massive and laggy delay when dragging the tabs across the titlebar. It's almost unusable and pretty slow. I haven't modified the code at all and I've tried, but it's not working. Has anyone else come across this problem and fixed it?

**Comment by bobowk** [comment] 2020-05-12 23:24
![ezgif-1-958a2012caed](https://user-images.githubusercontent.com/60067581/81755205-82c6f300-94fb-11ea-887e-f6a8e7250b6e.gif)

**Comment by lstratman** [comment] 2020-09-14 22:02
I apologize for taking this long, but I'm just starting up work on this project again.  If you're still interested in a solution, can you run the task manager while you're doing the dragging?  Is the CPU pegged?  If so, is it your application the one that's taking all of the CPU or it something else like antivirus?  Also, have you customized the tab renderer at all, like in the `Render()` method?

**Comment by lstratman** [comment] 2021-12-23 15:41
Closing this out since I wasn't able to reproduce.

**Closed by lstratman** 2021-12-23 15:41 UTC
