### ISSUE TITLE
Does not allow moving the tabs between vertical monitors

### ISSUE THREAD

**Issue by elipgo** [lstratman/EasyTabs#38] opened 2020-08-26 15:58 UTC
Hi

If the monitors are organized up/down, it does not accept to move it by dragging the window vertically, it allows to drag it only between monitors horizontally.

![image](https://user-images.githubusercontent.com/16120087/91324075-04374e00-e798-11ea-9109-f36c6cf0c409.png)

Thanks

**Comment by lstratman** [comment] 2020-09-14 22:06
I haven't been able to reproduce this on my side:  I've oriented two of my monitors vertically like you have above, and I'm able to drag the main window up into the second monitor and am also able to tear tabs off of the main window and drag them to the second window without any issues.  Are you using the latest version of this package in your application?  I've released a series of betas over the last few days in preparation for a 2.0 release, could you try the latest beta and see if the issue still exists?

**Comment by elipgo** [comment] 2020-11-09 20:00
Hi, When the application is Maximixed, it does not create the tab on the second vertical monitor and does not allow dragging to it.

I am using the 2.0 release .

**Comment by lstratman** [comment] 2021-12-23 15:42
Closing this out since I was not able to reproduce.

**Closed by lstratman** 2021-12-23 15:42 UTC
