### ISSUE TITLE
Closing program after closing last tab

### ISSUE THREAD

**Issue by jacksiro254** [lstratman/EasyTabs#19] opened 2019-02-09 01:57 UTC
I noticed when I closed the last tab or I simply close the entire program, it does not exit entirely but continues to stay in the background till I have to close with the task manager. Kindly help fix this or give us a hint on how to resolve this.

**Comment by vlogozzo** [comment] 2020-06-30 14:43
+1

**Comment by lstratman** [comment] 2020-09-13 15:29
I haven't been able to reproduce this on my side using either my test application or the other project I have that uses this library.  What does your main form class look like and what does the `Main()` method for your application look like?

**Comment by lstratman** [comment] 2021-12-23 15:41
Closing this out since I wasn't able to reproduce.

**Closed by lstratman** 2021-12-23 15:41 UTC
